application: qunachi
version: 1
runtime: python
api_version: 1

handlers:

- url: /resources
  static_dir: static/resources

- url: /static
  static_dir: static

- url: /(.*\.(js|css|gif|png))
  static_files: static/\1
  upload: static/(.*\.(js|css|gif|png))

- url: /.*
  script: index.py
